[project]
name = "anki-review-feedback"
version = "0.1.0"
description = "Provide feedback after answering a card, similar to AnkiDroid."
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "aqt",
    "mypy",
    "mypy-protobuf",
]
